CREATE DATABASE IF NOT EXISTS calendar_planer;

CREATE TABLE IF NOT EXISTS Events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  startTime BIGINT NOT NULL,
  endTime BIGINT NOT NULL,
  notes VARCHAR(255) NOT NULL,
  color VARCHAR(255) NOT NULL,
  dayOfMonth INT NOT NULL,
  month INT NOT NULL,
  year INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);